### ISSUE TITLE
Testers wanted for new dual-boot script

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricksdev#14]
We are considering a few ways to improve the Pybricks installer for SPIKE Prime and MINDSTORMS Robot Inventor. Ultimately, we'd like to provide something in [Pybricks Code](https://www.code.pybricks.com/). One promising solution seems to be web serial, which lets us talk to the hub via the USB cable.

Before we add it to the app, we're doing some tests in `pybricksdev`. This helps us test at least the hub side of things, before we implement it in the web app.

If you have previously installed `pybricksdev`, it would be great if you want to help us test this. Perhaps @BertLindeman, @jorgepe, @johnscary-ev3, @heyllama would be interested if you have some time to spare.

# Instructions
- Make sure you have the latest `pybricksdev`.
   - [Install if you haven't already](https://github.com/pybricks/pybricksdev)
   - If already installed previously, just updating is fine:
       - git pull
       - poetry install
- Boot the hub into the regular firmware and plug in USB.
- Download the latest firmware build, e.g. [this link](https://github.com/pybricks/pybricks-micropython/suites/1911390546/artifacts/37560434) and save it somewhere.
- Run this, and replace the download path with yours:

```
poetry run pybricksdev dual-boot path/to/the/downloaded/primehub-firmware.zip
```
There should be some output in the terminal. And all 25 pixels will turn on one by one. When done, it should reboot and install the firmware. Now it should work the same as before, so a long press will give you Pybricks.

**Comment by JorgePe** [comment]
Working fine in Ubuntu Linux
I previously added a udev rule, not sure if it was needed. Dmesg regognized the 51515 hub, pybricks dev worked with no problems:
```
Connecting to /dev/ttyACM0
Currently running dual-boot firmware.
Detected firmware:
{'size': 557056, 'version': 'v1.0.06.0034-b0c335b', 'checksum': 1231192444, 'boot_vector': b'\xc9Z\x08\x08'}
Backing up 557056 bytes of original firmware. Progress:
Backup complete

Preparing external flash.
Writing firmware. Progress:
Done! Verifying firmware.
Download succeeded. Rebooting now...
```
First time I connected with Chrome I tried REPL and could not write anything. Power off, power on again and REPL is fine.
Light example also working.
It feels so... clean. Thanks a lot!

**Comment by laurensvalk** [comment]
A backup file has also been created on your local folder. Just because 😄

**Comment by JorgePe** [comment]
'firmware-v1.0.06.0034-b0c335b.bin'
the name has any meaning? I mean, can I store this files and relate to them for a specific LEGO firmware version?

**Comment by laurensvalk** [comment]
It is the version reported by the stock firmware. Not sure what it means exactly, but higher is probably newer 😄 

You could use it to [restore the stock firmware](https://dfu.pybricks.com/) if you ever get tired of pybricks or dual boot for some reason.

**Comment by JorgePe** [comment]
I was more thinking on keeping my own collection of stock firmwares in case 4 or 5 years in the future the LEGO App ii withdraw.

**Comment by BertLindeman** [comment]
@laurensvalk Assumed that you meant the standard LEGO firmware with
> `the regular firmware`

trying to get pybricksdev installed on windows did not succeed on my PC.

So switching to Linux Mint 20.1 as these things are so much easier there..

First attempt failed:
```
Connecting to /dev/ttyACM0
Currently running dual-boot firmware.
Detected firmware:
{'size': 598016, 'version': 'v1.1.01.0002-3e5a121', 'checksum': 4069123311, 'boot_vector': b'\xa1A\t\x08'}
Backing up 598016 bytes of original firmware. Progress:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bert/Downloads/pybricksdev/pybricksdev/pybricksdev/cli/__init__.py", line 326, in main
    loop.run_until_complete(subparsers.choices[args.tool].tool.run(args))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/bert/Downloads/pybricksdev/pybricksdev/pybricksdev/cli/__init__.py", line 220, in run
    await installer.install(args.firmware.name)
  File "/home/bert/Downloads/pybricksdev/pybricksdev/pybricksdev/repl_installer.py", line 285, in install
    base_firmware_blob = await self.get_base_firmware_blob(base_firmware_info)
  File "/home/bert/Downloads/pybricksdev/pybricksdev/pybricksdev/repl_installer.py", line 185, in get_base_firmware_blob
    block = await self.get_flash_block(bytes_read)
  File "/home/bert/Downloads/pybricksdev/pybricksdev/pybricksdev/repl_installer.py", line 161, in get_flash_block
    return await self.exec_and_eval(
  File "/home/bert/Downloads/pybricksdev/pybricksdev/pybricksdev/repl_installer.py", line 56, in exec_and_eval
    return eval(await self.exec_line(line))
TypeError: eval() arg 1 must be a string, bytes or code object
```
10th pixel was 3/4 lit.

**retry**
```
Connecting to /dev/ttyACM0
Currently running dual-boot firmware.
Detected firmware:
{'size': 598016, 'version': 'v1.1.01.0002-3e5a121', 'checksum': 4069123311, 'boot_vector': b'\xa1A\t\x08'}
Backing up 598016 bytes of original firmware. Progress:
Backup complete

Preparing external flash.
Writing firmware. Progress:
Done! Verifying firmware.
Download succeeded. Rebooting now...
```

Auto reboot - OK

Boot into pybricks: `hub initiated ('primehub', '3.0.0b1', 'v3.0.0b1-6-g9fc79e68 on 2021-01-27')`

Connect to the Spike App also OKE.
Spike reports the firmware as:

![image](https://user-images.githubusercontent.com/8142081/106313167-0f6f3800-6268-11eb-8ca9-502869e5be71.png)

**Comment by laurensvalk** [comment]
Thanks for trying it as well. There should probably be some more error checking :)

The good news is that the real update doesn’t really start until the upload is successful, so there isn’t much that can go wrong, and trying again should work without restarts, so we can implement that as well.

**Comment by HeyLlama** [comment]
Detected firmware:
{'size': 557056, 'version': 'v1.0.06.0034-b0c335b', 'checksum': 1231192444, 'boot_vector': b'\xc9Z\x08\x08'}
Backing up 557056 bytes of original firmware. Progress:
Backup complete

Preparing external flash.
Writing firmware. Progress:
Done! Verifying firmware.
Download succeeded. Rebooting now...

Can confirm dual boot and everything work as expected ;D

**Comment by BertLindeman** [comment]
Not SURE if poetry pyenv etc is correctly installed on my win10 PC, . . . . 

Python3 on my PC is 3.9 but I did `pyenv local 3.8.2` here, and poetry does not complain about that.
But I think it's strange to see python39 in the messages:
``` console
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
```

Console log (have split the first line for readability):
``` console
C:\Users\bert.grijshuid\Downloads\Lego\Pybricks\pybricksdev\pybricksdev>
poetry run pybricksdev dual-boot C:\Users\bert.grijshuid\Downloads\Lego\Pybricks\primehub-firmware_for_dualb
oot_test.zip
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\bert.grijshuid\Downloads\Lego\Pybricks\pybricksdev\pybricksdev\pybricksdev\cli\__init__.py", line 10, in <module>
    import validators
ModuleNotFoundError: No module named 'validators'
```

This goes much further than my rudimentary knowledge of python ;-)

**Comment by dlech** [comment]
I don't recommend using `pyenv` on windows. The default installer comes with the Python Launcher for Windows which makes things easier.

Assuming the launcher is installed, you can run `py --list-paths` to see the full paths of all installed Python versions. Then use `poetry env` to set the Python path for Poetry to the path to the 3.8.x install.

**Comment by dlech** [comment]
You can also run `poetry env info` to see what Poetry is currently using.

**Comment by johnscary-ev3** [comment]
@laurensvalk 
I tried this on my Win 10 PC which has Python 3.8 and previous version of pybricksdev installed. So I used the "update" option.
At first the "poetry install" step failed, but then I recalled having to remove .venv directory and poetry.lock file first.
After doing that, the poetry install worked, and then I was able to install the hub firmware using the command you gave and USB connection.
The hub is working fine again using BLE and VS Code after a reboot into Pybricks mode.
Thanks for working on this.
Much better than having to use the LEGO app  ;0)

**Comment by BertLindeman** [comment]
> I don't recommend using `pyenv` on windows. The default installer comes with the Python Launcher for Windows which makes things easier.
> 
> Assuming the launcher is installed, you can run `py --list-paths` to see the full paths of all installed Python versions. Then use `poetry env use <path>` to set the Python path for Poetry to the path to the 3.8.x install.
> 
> Or if you installed Python from the Windows Store, you should be able to run `poetry env use python38`.

Thanks, David.
That helps to get rid of the python39 part. So a more consistent environment.
Now onto the post of  @johnscary-ev3

**Comment by laurensvalk** [comment]
Thanks everyone for your quick responses! So it looks like we’ve got it working on Linux, Mac, and Windows, and for several hubs as well. That’s what I was after, thanks!

Don’t worry about poetry on Windows for this Bert - if it was working on Linux for you then that’s fine.

This was more about getting some feeling for whether this installation approach is a good idea. Both technically and the user experience. It seems that the answer is yes, so now we can consider doing it properly in Pybricks Code, instead of hacking around with pybricksdev.

**Comment by BertLindeman** [comment]
> 
> 
> Thanks everyone for your quick responses! So it looks like we’ve got it working on Linux, Mac, and Windows, and for several hubs as well. That’s what I was after, thanks!
> 
> Don’t worry about poetry on Windows for this Bert - if it was working on Linux for you then that’s fine.
> 
> This was more about getting some feeling for whether this installation approach is a good idea. Both technically and the user experience. It seems that the answer is yes, so now we can consider doing it properly in Pybricks Code, instead of hacking around with pybricksdev.

Thanks, Laurens, I will not worry about poetry.
So, awaiting the next test situation ;-)

**Comment by laurensvalk** [comment]
Can I make another request? :smile: 

It's nothing much yet, but can you test that you are able to connect and toggle the lights of the hub using this page?

https://beta.pybricks.com/

Make sure USB is connected and you are booted into the stock firmware.

**Comment by BertLindeman** [comment]
> Can I make another request? 😄

naughty: Hi hi Laurens, you just **did** 😃 end-naughty

Sure, will look into it tomorrow.

**Comment by johnscary-ev3** [comment]
@laurensvalk 
This worked on my Win 10 PC, but first I had to Enable this Chrome Flags setting:

```
Experimental Web Platform features
Enables experimental Web Platform features that are in development. – Mac, Windows, Linux, Chrome OS, Android
#enable-experimental-web-platform-features
```

**Comment by BertLindeman** [comment]
> Sure will look into it tomorrow.

Sorry, Laurens, I cannot keep my promise...
Curiosity took over...

Just tested (win10 - MSEDGE)
MSedge  did not need any experimental setting


Saw this:
![image](https://user-images.githubusercontent.com/8142081/106668576-b7f40380-65aa-11eb-971d-7e8a984107ee.png)


**And Light-switch works**  
:smile:

**Comment by laurensvalk** [comment]
Thanks both for the quick response.

And good to know about Microsoft Edge too, thanks for trying!

**Comment by johnscary-ev3** [comment]
On my win 10 using Edge I got this error which is why I tried Chrome:

![image](https://user-images.githubusercontent.com/62860364/106672052-4d1fd980-6564-11eb-8b63-9cf359448b66.png)

**Comment by BertLindeman** [comment]
My previous post was using the Spikehub
On MSEDGE Versie 88.0.705.56 (Officiële build) (64-bits)
The `enable-experimental-web-platform-features`
were already enabled, via `edge://flags/`

**Complication**

Now trying to do the same with the inventorhub does not succeed.
Also tried on Chrome (enabled `enable-experimental-web-platform-features`)
- web page comes up ok.
- plug in USB - hub auto boots.
- click `connect`
- the serial connect pop-up comes up
- select the serial com port and `connect`
Look slike nothing happens.

I see more than one serial port in the select list:
![image](https://user-images.githubusercontent.com/8142081/106671949-8b8eb600-65af-11eb-87b7-4c54b7605877.png)

On the console I see:
```
script.js:63 Uncaught (in promise) DOMException: No port selected by the user.
connectButtonHandler @ script.js:63
async function (async)
connectButtonHandler @ script.js:59
script.js:198 Uncaught (in promise) DOMException: Failed to execute 'close' on 'SerialPort': The port is already closed.
    at disconnect (https://beta.pybricks.com/script.js:198:16)
    at HTMLButtonElement.connectButtonHandler (https://beta.pybricks.com/script.js:53:15)
disconnect @ script.js:198
connectButtonHandler @ script.js:53
async function (async)
connectButtonHandler @ script.js:53
script.js:63 Uncaught (in promise) DOMException: Failed to open serial port.
connectButtonHandler @ script.js:63
async function (async)
connectButtonHandler @ script.js:59
```
No idea if this is any help.
Did this both on MSEDGE and chrome

opened the message:
```
script.js:63 Uncaught (in promise) DOMException: Failed to open serial port.
connectButtonHandler @ script.js:63
async function (async)
connectButtonHandler @ script.js:59
```

**Comment by BertLindeman** [comment]
Hmm, the inventor app does not connect too via USB . . . . . . 

Going to debug that first

**Comment by JorgePe** [comment]
Chrome Version 88.0.4324.96 (Official Build) (64-bit) on Ubuntu working with 51515 Robot Inventor hub

**Comment by laurensvalk** [comment]
@BertLindeman, I have that problem also sometimes.

But I've always had this with the SPIKE/Inventor hub for some reason, causing even a `screen` terminal not to work, or the regular app. When things do connect, I've also sometimes noticed the hub spitting out a few characters within the first couple of minutes after boot.

I have not yet investigated what that is, but it doesn't seem related to the browser per se, as it seems to happen with all apps.

**Comment by laurensvalk** [comment]
@BertLindeman 

Assuming you already have the pybricks udev rules, try adding these too:

```
# Extra TTY rules
ATTRS{idVendor}=="0694", ENV{ID_MM_DEVICE_IGNORE}="1"
ATTRS{idVendor}=="0694", ENV{MTP_NO_PROBE}="1"
KERNEL=="ttyACM*", ATTRS{idVendor}=="0694", MODE:="0666"
```

I found them [here](https://forum.micropython.org/viewtopic.php?t=1287), and things started working afterward. @dlech may be able to chime in to say which of these is really needed and which is not.

**Comment by BertLindeman** [comment]
> 
> 
> @BertLindeman
> 
> Assuming you already have the pybricks udev rules, try adding these too:
> 
> ```
> # Extra TTY rules
> ATTRS{idVendor}=="0694", ENV{ID_MM_DEVICE_IGNORE}="1"
> ATTRS{idVendor}=="0694", ENV{MTP_NO_PROBE}="1"
> KERNEL=="ttyACM*", ATTRS{idVendor}=="0694", MODE:="0666"
> ```
> 
> I found them [here](https://forum.micropython.org/viewtopic.php?t=1287), and things started working afterward. @dlech may be able to chime in to say which of these is really needed and which is not.

Most of the time I use windows as it's almost constantly within reach.
AND I forgot to say so in the post above. Sorry  :smile: 
Will wait for response of @dlech and may then add them to my Linux Mint system.
Thank you.

**Comment by dlech** [comment]
> ATTRS{idVendor}=="0694", ENV{ID_MM_DEVICE_IGNORE}="1"

This one makes sense.

> ATTRS{idVendor}=="0694", ENV{MTP_NO_PROBE}="1"

Does it still work if we leave this one out?

> KERNEL=="ttyACM*", ATTRS{idVendor}=="0694", MODE:="0666"

This should already be taken care of if the user is in the `dialout` group, but I suppose it wouldn't hurt to add it. Although I would probably use the more generic `SUBSYSTEMS=="tty"` instead of `KERNEL=="ttyACM*"`.

**Comment by laurensvalk** [comment]
If anyone is feeling adventurous, there's a bit more to [test now](https://beta.pybricks.com/).... :rocket:

**Comment by BertLindeman** [comment]
Early experience on win10 + MSEDGE:

![image](https://user-images.githubusercontent.com/8142081/107114029-24992780-6863-11eb-851e-18b744f76198.png)

No indication of ```LEGO Technic Large Hub in FS mode``` see the screenshot above.

Next after selecting a firmware zip file the butInstall is not enabled, see below:

![image](https://user-images.githubusercontent.com/8142081/107114164-30d1b480-6864-11eb-8c13-ae5bb4a4d6dd.png)

**Comment by BertLindeman** [comment]
Looks like it is possible to connect the hub from more than one browser. 
Or even from more than one tab in a browser.

But that is at this stage not of interest I think.

**Comment by BertLindeman** [comment]
@laurensvalk  do we need the dual-boot zip file for this, **not** a recent firmware zip?

**Comment by laurensvalk** [comment]
Any fairly recent zip should work. Also make sure that you boot into the standard firmware to try this.

**Comment by BertLindeman** [comment]
Used
 ```
C:\Users\bert.grijshuid\Downloads\Lego\Pybricks>unzip -l primehub-firmware_20210128.zip
Archive:  primehub-firmware_20210128.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   301260  2021-01-27 16:13   download_pybricks.llsp
   301263  2021-01-27 16:13   download_pybricks.lms
   208816  2021-01-27 16:13   firmware-base.bin
   209596  2021-01-27 16:13   firmware-dual-boot-base.bin
      283  2021-01-27 16:13   firmware.metadata.json
    13877  2021-01-27 16:13   install_pybricks.llsp
    13880  2021-01-27 16:13   install_pybricks.lms
      111  2021-01-27 16:13   main.py
    24248  2021-01-27 16:13   ReadMe_OSS.txt
---------                     -------
  1073334                     9 files
``` 

This contains the `"firmware-dual-boot-base.bin"` that the script wants. I think.

Another possibility is the file type?
From the console - text copy:
```
File {name: "primehub-firmware_20210128.zip", lastModified: 1611860434183, lastModifiedDate: Thu Jan 28 2021 20:00:34 GMT+0100 (Midden-Europese standaardtijd), webkitRelativePath: "", size: 676712, …}lastModified: 1611860434183lastModifiedDate: Thu Jan 28 2021 20:00:34 GMT+0100 (Midden-Europese standaardtijd) {}name: "primehub-firmware_20210128.zip"size: 676712type: "application/x-zip-compressed"webkitRelativePath: ""__proto__: File
script.ts:81 
```
type reported here `application/x-zip-compressed` the script looks for `application/zip`

**Comment by BertLindeman** [comment]
> Also make sure that you boot into the standard firmware to try this.

If the hub is OFF and you plug-in USB. the hub automatically boots LEGO firmware.
A handy feature :smile:

**Comment by laurensvalk** [comment]
Yes, that’s the right file.

**Comment by BertLindeman** [comment]
Ran the test on Linux Mint - OK

- had to add my user to the `dialout` group and restart the session to allow the use of /dev/ttyACM1 
- saw the LEGO? firmware downloaded as  ```firmware-backup-v1.0.06.0034-b0c335.bin```
- auto-reboot OK
- LEGO boot OK
- Pybricks boot OK

So no problem on Linux Mint 20.1

**Comment by laurensvalk** [comment]
@BertLindeman, the issue on Windows might be resolved now.

**Comment by BertLindeman** [comment]
Win10  - MS Edge Versie 88.0.705.63 (Officiële build) (64-bits)
Firmware update to Spike prime hub.

```
Installation progress: 100%

Ready to install.
Installing now...
Something went wrong. Please refresh the page and try again.
```

Could not copy the messages as text, so as a screenshot:

![image](https://user-images.githubusercontent.com/8142081/107786657-73a4f800-6d4e-11eb-9411-89a68dfd6b35.png)

Took USB out and rebooted the hub. The hub neatly flashes red-green-blue and reboots ok.
Firmware reported as
```
('primehub', '3.0.0b1', 'v3.0.0b1-17-g576d0897 on 2021-02-08')
```

Will do the refresh as the message states . . .
And report in the next post.

**Comment by laurensvalk** [comment]
Should be fixed now. Maybe do a hard refresh (CTRL+F5) to make sure you have the latest version of the page.

**Comment by BertLindeman** [comment]
After click on `connect`  MSedge crashed.


Microsoft Edge is updated in the meantime
Versie 88.0.705.68 (Officiële build) (64-bits)

retrying:
SAME result: 
After click on `connect`  MSedge crashed.
(Typing this in MSedge, so let me save this comment)

**Comment by laurensvalk** [comment]
Did it not crash before?

**Comment by BertLindeman** [comment]
No crash before.

Now "did" Chrome Version 88.0.4324.150 (Official Build) (64-bit) and that went all **OKE** including reboot to install the new firmware.

Page was like this after install:
```
Connect the hub via USB.
Click Connect and select the LEGO Technic Large Hub in FS mode.
Click Install to begin the update.
 If you like, download a backup of the original firmware: firmware-backup-v1.0.06.0034-b0c335.bin
If needed, start over by refreshing the page.
Installation progress: 100%

Ready to install.
Creating back up of original firmware...
Copying dual-boot firmware to the hub...
File transfer complete. The hub will now reboot to install the new firmware!
```

Will reboot PC and retry MSEDGE after that.

**Comment by BertLindeman** [comment]
Problem in MSEDGE is **not** related to pybricks.
After a normal start of edge a close of a tab crashed also.

retry on msedge is good:
```
Connect the hub via USB.
Click Connect and select the LEGO Technic Large Hub in FS mode.
Click Install to begin the update.
 If you like, download a backup of the original firmware: firmware-backup-v1.0.06.0034-b0c335.bin
If needed, start over by refreshing the page.
Installation progress: 100%

Ready to install.
Creating back up of original firmware...
Copying dual-boot firmware to the hub...
File transfer complete. The hub will now reboot to install the new firmware!
```

Console as screenprint:
![image](https://user-images.githubusercontent.com/8142081/107794939-5aa14480-6d58-11eb-9ada-b12e51f0410b.png)

**Comment by laurensvalk** [comment]
That looks good. Thank you!
