### ISSUE TITLE
AccessDenied error when trying to flash firmware to Technic hub from Windows

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricksdev#15]
I'm pretty sure this is a bug in the LEGO bootloader combined with the way the Windows Bluetooth stack works combined with the way Bleak works. So we might be able to work around this by fixing Bleak.

Running the command

```
pybricksdev flash .\bricks\technichub\build\firmware.zip -d5
```

gives

```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code  
    exec(code, run_globals)
  File "C:\Users\david\Documents\GitHub\Pybricks\pybricks-micropython\.venv\Scripts\pybricksdev.exe\__main__.py", line 7, in <module>        
  File "c:\users\david\documents\github\pybricks\pybricks-micropython\.venv\lib\site-packages\pybricksdev\cli\__init__.py", line 326, in main    loop.run_until_complete(subparsers.choices[args.tool].tool.run(args))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\david\documents\github\pybricks\pybricks-micropython\.venv\lib\site-packages\pybricksdev\cli\__init__.py", line 198, in run 
    await updater.connect(device)
  File "c:\users\david\documents\github\pybricks\pybricks-micropython\.venv\lib\site-packages\pybricksdev\ble.py", line 139, in connect      
    await self.client.connect(disconnected_callback=self.disconnected_handler)
  File "c:\users\david\documents\github\pybricks\pybricks-micropython\.venv\lib\site-packages\bleak\backends\dotnet\client.py", line 243, in 
connect
    await self.get_services()
  File "c:\users\david\documents\github\pybricks\pybricks-micropython\.venv\lib\site-packages\bleak\backends\dotnet\client.py", line 464, in 
get_services
    raise BleakDotNetTaskError(
bleak.exc.BleakDotNetTaskError: Could not get GATT characteristics for Windows.Devices.Bluetooth.GenericAttributeProfile.GattDeviceService: AccessDenied
```

Windows Bluetooth capture.

[bth_hci.zip](https://github.com/pybricks/pybricksdev/files/6253374/bth_hci.zip)

In the Bluetooth capture, we can see that the hub claims that it claims that it has a Service Changed characteristic with indications

```
Frame 44: 17 bytes on wire (136 bits), 17 bytes captured (136 bits)
Bluetooth
Bluetooth HCI H1 Rcvd ACL Data
Bluetooth HCI ACL Packet
Bluetooth L2CAP Protocol
Bluetooth Attribute Protocol
    Opcode: Read By Type Response (0x09)
    Length: 7
    Attribute Data, Handle: 0x0002, Characteristic Handle: 0x0003, UUID: Service Changed
        Handle: 0x0002 (GATT Characteristic Declaration)
        Characteristic Properties: 0x20, Indicate
        Characteristic Value Handle: 0x0003 (Service Changed)
        UUID: Service Changed (0x2a05)
    [UUID: GATT Characteristic Declaration (0x2803)]
    [Request in Frame: 42]
```

Windows tries to enable indications on this characteristic

```
Frame 51: 13 bytes on wire (104 bits), 13 bytes captured (104 bits)
Bluetooth
Bluetooth HCI H1 Sent ACL Data
Bluetooth HCI ACL Packet
Bluetooth L2CAP Protocol
Bluetooth Attribute Protocol
    Opcode: Write Request (0x12)
    Handle: 0x0004 (Service Changed: Client Characteristic Configuration)
    Characteristic Configuration Client: 0x0002, Indication
        0000 0000 0000 00.. = Reseved: 0x0000
        .... .... .... ..1. = Indication: True
        .... .... .... ...0 = Notification: False
```

But the hub replies with an error.

```
Frame 53: 13 bytes on wire (104 bits), 13 bytes captured (104 bits)
Bluetooth
Bluetooth HCI H1 Rcvd ACL Data
Bluetooth HCI ACL Packet
Bluetooth L2CAP Protocol
Bluetooth Attribute Protocol
    Opcode: Error Response (0x01)
    Request Opcode in Error: Write Request (0x12)
    Handle in Error: 0x0004 (Service Changed: Client Characteristic Configuration)
    Error Code: Write Not Permitted (0x03)
```

There are a few more characteristic enumeration packets sent back and forth after this, but I have a feeling that this error bubbles up in Bleak which causes the connect method to fail since the connect method also enumerates services (and I suppose characteristics)

**Comment by thesynman** [comment]
I've seen this error, but it went away after I rebooted Windows.

**Comment by dlech** [comment]
Same here. So maybe the solution is to add a better error message when this happens to tell the user to try rebooting.

**Comment by dlech** [comment]
I got this again today. I had previously connected to the device in a web browser. Even though the device was no longer connected i the web browser, apparently, it still had a handle on it. After closing the web browser (all windows), I was able to use `pybricksdev` without restarting the computer.
