### ISSUE TITLE
Error in installing pybricksdev on raspberry

### ISSUE THREAD

**Issue by mnrlmnstr** [pybricks/pybricksdev#51]
Hi!

I'm trying to install pybrickdev on rapberrypi 3 model b: `pip3 install pybricksdev --pre`

Everything installing correctly. Only issue with `mpy-cross-v5` and `mpy-cross-v6` dependencies.
As I understood this is special version of mpy-cross for this project?
Regular `mpy-cross` installs without any issues. 

Also have this problems if installing using `pipx`. Have no any problems with installation on Macbook Pro M1.
Appreciate any help, thanks

### Environment
```
python 3.9.2
pip 23.0
setuptools 67.3.1

Linux 5.15.61-v7+ 
armv7l
Raspbian GNU/Linux 11 (bullseye)
```
### Installation errors
```
Building wheels for collected packages: mpy-cross-v5, mpy-cross-v6
  Building wheel for mpy-cross-v5 (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for mpy-cross-v5 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [64 lines of output]
      /tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/mpy_cross_v5
      copying src/mpy_cross_v5/__main__.py -> build/lib/mpy_cross_v5
      copying src/mpy_cross_v5/__init__.py -> build/lib/mpy_cross_v5
      running egg_info
      writing src/mpy_cross_v5.egg-info/PKG-INFO
      writing dependency_links to src/mpy_cross_v5.egg-info/dependency_links.txt
      writing entry points to src/mpy_cross_v5.egg-info/entry_points.txt
      writing top-level names to src/mpy_cross_v5.egg-info/top_level.txt
      reading manifest file 'src/mpy_cross_v5.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'micropython/mpy-cross/build*'
      no previously-included directories found matching 'micropython/ports*'
      warning: no previously-included files found matching 'src/mpy_cross_v5/mpy-cross*'
      writing manifest file 'src/mpy_cross_v5.egg-info/SOURCES.txt'
      make: Entering directory '/tmp/pip-install-p0qb8eao/mpy-cross-v5_e00d7b26be71488ca5a9cfaff8de7a54/micropython/mpy-cross'
      Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
      ../py/py.mk:289: ../extmod/extmod.mk: No such file or directory
      make: *** No rule to make target '../extmod/extmod.mk'.  Stop.
      make: Leaving directory '/tmp/pip-install-p0qb8eao/mpy-cross-v5_e00d7b26be71488ca5a9cfaff8de7a54/micropython/mpy-cross'
      Traceback (most recent call last):
        File "/home/ml/Development/remote-machine/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ml/Development/remote-machine/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ml/Development/remote-machine/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 79, in <module>
        File "/tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-eerkmbtn/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 52, in run
        File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['make', '-C', PosixPath('/tmp/pip-install-p0qb8eao/mpy-cross-v5_e00d7b26be71488ca5a9cfaff8de7a54/micropython/mpy-cross'), 'BUILD=build-linux-armv7l']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mpy-cross-v5
  Building wheel for mpy-cross-v6 (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for mpy-cross-v6 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]
      /tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/mpy_cross_v6
      copying src/mpy_cross_v6/__main__.py -> build/lib/mpy_cross_v6
      copying src/mpy_cross_v6/__init__.py -> build/lib/mpy_cross_v6
      running egg_info
      writing src/mpy_cross_v6.egg-info/PKG-INFO
      writing dependency_links to src/mpy_cross_v6.egg-info/dependency_links.txt
      writing entry points to src/mpy_cross_v6.egg-info/entry_points.txt
      writing top-level names to src/mpy_cross_v6.egg-info/top_level.txt
      reading manifest file 'src/mpy_cross_v6.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'micropython/mpy-cross/build*'
      no previously-included directories found matching 'micropython/ports*'
      warning: no previously-included files found matching 'src/mpy_cross_v6/mpy-cross*'
      writing manifest file 'src/mpy_cross_v6.egg-info/SOURCES.txt'
      make: Entering directory '/tmp/pip-install-p0qb8eao/mpy-cross-v6_ce0835038be947d289e34dd64d96afb5/micropython/mpy-cross'
      Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
      mkdir -p build-linux-armv7l/genhdr
      GEN build-linux-armv7l/genhdr/mpversion.h
      GEN build-linux-armv7l/genhdr/qstr.i.last
      ../py/modsys.c:39:10: fatal error: extmod/moduplatform.h: No such file or directory
         39 | #include "extmod/moduplatform.h"
            |          ^~~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      Traceback (most recent call last):
        File "/tmp/pip-install-p0qb8eao/mpy-cross-v6_ce0835038be947d289e34dd64d96afb5/micropython/mpy-cross/../py/makeqstrdefs.py", line 203, in <module>
          preprocess()
        File "/tmp/pip-install-p0qb8eao/mpy-cross-v6_ce0835038be947d289e34dd64d96afb5/micropython/mpy-cross/../py/makeqstrdefs.py", line 73, in preprocess
          for output in p.imap(pp(flags), chunks):
        File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
          raise value
        File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/tmp/pip-install-p0qb8eao/mpy-cross-v6_ce0835038be947d289e34dd64d96afb5/micropython/mpy-cross/../py/makeqstrdefs.py", line 57, in run
          return subprocess.check_output(args.pp + flags + files)
        File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['gcc', '-E', '-I.', '-Ibuild-linux-armv7l', '-I..', '-Wall', '-Werror', '-Wextra', '-Wno-unused-parameter', '-Wpointer-arith', '-std=gnu99', '-Os', '-fdata-sections', '-ffunction-sections', '-fno-asynchronous-unwind-tables', '-DNO_QSTR', '../py/objzip.c', '../py/opmethods.c', '../py/sequence.c', '../py/stream.c', '../py/binary.c', '../py/builtinimport.c', '../py/builtinevex.c', '../py/builtinhelp.c', '../py/modarray.c', '../py/modbuiltins.c', '../py/modcollections.c', '../py/modgc.c', '../py/modio.c', '../py/modmath.c', '../py/modcmath.c', '../py/modmicropython.c', '../py/modstruct.c', '../py/modsys.c', '../py/moduerrno.c', '../py/modthread.c', '../py/vm.c', '../py/bc.c', '../py/showbc.c', '../py/repl.c', '../py/smallint.c', '../py/frozenmod.c']' returned non-zero exit status 1.
      make: *** [../py/mkrules.mk:108: build-linux-armv7l/genhdr/qstr.i.last] Error 1
      make: *** Deleting file 'build-linux-armv7l/genhdr/qstr.i.last'
      make: Leaving directory '/tmp/pip-install-p0qb8eao/mpy-cross-v6_ce0835038be947d289e34dd64d96afb5/micropython/mpy-cross'
      Traceback (most recent call last):
        File "/home/ml/Development/remote-machine/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ml/Development/remote-machine/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ml/Development/remote-machine/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 79, in <module>
        File "/tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-s_9j_jm6/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 52, in run
        File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['make', '-C', PosixPath('/tmp/pip-install-p0qb8eao/mpy-cross-v6_ce0835038be947d289e34dd64d96afb5/micropython/mpy-cross'), 'BUILD=build-linux-armv7l']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mpy-cross-v6
Failed to build mpy-cross-v5 mpy-cross-v6
ERROR: Could not build wheels for mpy-cross-v5, mpy-cross-v6, which is required to install pyproject.toml-based projects
```

**Comment by dlech** [comment]
Hmm... it looks like we might be missing some files in the source package.

And it looks like the piwheels builds are failing:

- https://www.piwheels.org/project/mpy-cross-v5/
- https://www.piwheels.org/project/mpy-cross-v6/

I will look in to it.

**Comment by dlech** [comment]
The mpy-cross package issues are fixed. However, install still fails on RPi because of the `crytography` package: https://github.com/piwheels/packages/issues/329. 

This should not be a critical dependency unless you are trying to connect to ev3dev using SSH.

**Comment by dlech** [comment]
Workaround is to call it like this:

    pipx run --pip-args "--only-binary :all:" pybricksdev

**Comment by mnrlmnstr** [comment]
Thanks! Everything installing correctly now.
