### ISSUE TITLE
Use pybricksdev programmatically

### ISSUE THREAD

**Issue by KonerDev** [pybricks/pybricksdev#64]
I want to run code on my hub using a Python script not the command, how is that possible?

**Comment by dlech** [comment]
FYI, the best place to ask questions about anything Pybricks is https://github.com/orgs/pybricks/discussions


Here is a basic script to get you started:

```python
#!/usr/bin/env python3

# run this script on your computer

import asyncio
import contextlib

from pybricksdev.ble import find_device
from pybricksdev.connections.pybricks import PybricksHub

# this script must be in the current working directory and will be sent to the hub
MY_PROGRAM = "hub_program.py"

async def main():
    async with contextlib.AsyncExitStack() as stack:
        dev = await find_device()
        hub = PybricksHub()
        await hub.connect(dev)
        stack.push_async_callback(hub.disconnect)
        await hub.run(MY_PROGRAM, print_output=True, wait=True)

asyncio.run(main())
```

**Comment by TheNicestDev** [comment]
Oh thanks, I didn't know that. And with the script I get an error:
```
Traceback (most recent call last):
  File "C:\Koner\projects\python\robi-ai\connect-tests\main.py", line 18, in <module>
    asyncio.run(main())
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Koner\projects\python\robi-ai\connect-tests\main.py", line 11, in main
    dev = await find_device()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\pybricksdev\ble\__init__.py", line 63, in find_device
    device = await BleakScanner.find_device_by_filter(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\bleak\__init__.py", line 369, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\bleak\__init__.py", line 152, in __aenter__
    await self._backend.start()
  File "C:\Users\Koner\AppData\Local\Programs\Python\Python311\Lib\site-packages\bleak\backends\winrt\scanner.py", line 241, in start
    self.watcher.start()
OSError: [WinError -2147020577] Das Gerät kann nicht verwendet werden
```
This means `The device cannot be used` in English

**Comment by TheNicestDev** [comment]
It looks like this is because bluetooth was turned off. How can I turn it on automatically?

**Comment by TheNicestDev** [comment]
And I still have one question, is it also possible to send individual commands instead of entire files?

**Comment by dlech** [comment]
It is, but the only available commands are to download a file or run a file that has already been downloaded to the hub or stop a running program. 

But you can write a program that runs on the hub that receives commands from the program running on your computer.

**Comment by TheNicestDev** [comment]
Do you have an example of this? And on the [code.pybricks.com](https://code.pybricks.com) website you can also execute individual commands, how does it work there?

**Comment by dlech** [comment]
There are some examples at https://pybricks.com/projects/tutorials/wireless/hub-to-device/

**Comment by TheNicestDev** [comment]
Thank you, but can I somehow write the code shown in the resource you gave me into one single file? So first I would need to connect with the hub using this code, right?

```py
device = await find_device()
hub = PybricksHub()
await hub.connect(device)
```

Then somehow upload the hub program (of course, the command doesn't work as shown):

```py
hub.upload_program('hub_program.py')
```

Then start it:

```py
hub.run_program()
```

And afterward, I would need to send the commands. Can't I do this somehow using:

```py
hub.write(b"fwd")
```

instead of using BleakClient?

**Comment by dlech** [comment]
Yes, you can do that using `pybricksdev`.

**Comment by dlech** [comment]
I thinks this is what you are looking for

https://github.com/pybricks/pybricksdev/blob/11667cb05427b2638fb475c1561fdfa380f59998/pybricksdev/connections/pybricks.py#L431

**Comment by dlech** [comment]
> 1. How can I use `hub.run()` without the tqdm progress bar

You can set the environment variable `TQDM_DISABLE=1`.




> 2\. How can I receive the data that the hub sends to the computer. With `hub.read_line()`?

Yes, this is the simplest way.



> 3\. How can I send commands to the hub that have different lengths, for example up to 20 characters

There is also a `write_line()` method.

**Comment by dlech** [comment]
The hub program doesn't take into account newlines. Also, if everything is text-based, we should be able to use `stdin` directly instead of `stdin.buffer`.

Also, the program on the computer should wait for something like an "OK" from the hub first before sending commands so that it knows that the hub program is loaded and running.

**Comment by dlech** [comment]
It looks like this program still sends the OK at the end instead of at the beginning. Also, it looks like it is doing a `read()` instead of `readline()`.

**Comment by dlech** [comment]
The OK is still at the end instead of the beginning on the hub program and the PC program does not wait for OK before sending each command.

**Comment by dlech** [comment]
This is how I would do it:

### main.py

```python
import asyncio
import contextlib
import os

# must before tqdm import!
os.environ["TQDM_DISABLE"] = "1"

from pybricksdev.ble import find_device
from pybricksdev.connections.pybricks import PybricksHub


async def connect_to_hub():
    try:
        device = await find_device()
        hub = PybricksHub()
        await hub.connect(device)
        return hub
    except asyncio.TimeoutError:
        raise RuntimeError("No device found")
    except OSError:
        raise RuntimeError("Please turn bluetooth on")


async def wait_ok(hub: PybricksHub):
    line = await asyncio.wait_for(hub.read_line(), timeout=5)

    if line != "OK":
        raise RuntimeError(f"Unexpected response: '{line}'")


async def stop_if_running(hub: PybricksHub):
    try:
        await hub.stop_user_program()
    except Exception:
        # ignore error, e.g. if hub is already disconnected
        pass


async def main():
    async with contextlib.AsyncExitStack() as stack:
        hub = await connect_to_hub()
        stack.push_async_callback(hub.disconnect)

        await hub.run("hub.py", print_output=False, wait=False)
        stack.push_async_callback(stop_if_running, hub)

        await wait_ok(hub)
        await hub.write_line("rev")

        await asyncio.sleep(3)

        await wait_ok(hub)
        await hub.write_line("fwd")

        await asyncio.sleep(3)

        await wait_ok(hub)
        await hub.write_line("bye")


asyncio.run(main())
```

### hub.py

```python
from pybricks.pupdevices import Motor
from pybricks.parameters import Port

# Standard MicroPython modules
from usys import stdin

motor = Motor(Port.A)

while True:
    # let PC know we are ready for a command
    print("OK")

    cmd = stdin.readline().strip()

    # Decide what to do based on the command.
    if cmd == "fwd":
        motor.dc(50)
    elif cmd == "rev":
        motor.dc(-50)
    elif cmd == "bye":
        break
```

**Comment by dlech** [comment]
You can only use one `asyncio.run()` in your script.

**Comment by dlech** [comment]
Pybricks does not support threading. The current beta version supports cooperative multitasking with coroutines (async/await). I don't think we have much documentation on it yet though.

**Comment by dlech** [comment]
> And where can I get the beta firmware?

https://beta.pybricks.com

> And should I just "install" the beta over the old version or should I first uninstall the old one and then install the beta?

These are independent applications. One does not replace the other.

> Can you show me the code with this cooperative multitasking?

```python
from pybricks.pupdevices import Motor
from pybricks.parameters import Port, Color
from pybricks.hubs import InventorHub
from pybricks.tools import wait, multitask, run_task
from usys import stdin
import random

# [...]

# Setup hub
hub = InventorHub()
hub.light.off()

# Face animation
animatedFaceFrames = [
    ((100, 100, 0, 100, 100), (100, 100, 0, 100, 100), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0)),
    ((0, 0, 0, 0, 0), (70, 70, 0, 70, 70), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0)),
    ((0, 0, 0, 0, 0), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0)),
    ((0, 0, 0, 0, 0), (80, 80, 0, 80, 80), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0)),
    ((100, 100, 0, 100, 100), (100, 100, 0, 100, 100), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0)),
]

async def animatedFaceController():
    while True:
        for frame in animatedFaceFrames:
            hub.display.icon(frame)
            await wait(50)
        await wait(random.uniform(1, 5))

async def other_task():
    ...

async def main():
    await multitask(
        animatedFaceController(),
        other_task(),
    )

run_task(main())
```

**Comment by dlech** [comment]
You have to flash the firmware on the hub to change it. You can't have two firmwares installed at the same time. You can read the current version of the firmware on the hub in the status bar of the Pybricks Code/Pybricks Beta web apps or you can write a program.

```python
from pybricks import version

print(version)
```

**Comment by dlech** [comment]
Change `random` to `urandom`.

**Comment by dlech** [comment]
`animatedFaceController()` is missing `await` before each call to `wait` so it will never yield.

`main()` needs an `await` in it somewhere inside of the while loop. If nothing else, at least `await wait(0)` at the end of the loop.

Blocking functions like `readline()` should not be used in async functions because they block everything else in the program from running. Instead, you can use `from pybricks.tools import read_input_byte` to read input in a non-blocking way.

I'm not really sure why you would be getting a memory error other than from memory fragmentation. Adding the required awaits should help with this since the main `run_task()` runs the garbage collector on each iteration.

**Comment by dlech** [comment]
Defining a class inside of a while loop doesn't seem like a good idea since it would redefine the class on each loop. Since you never create an instance of the class, it seems like it would be better to just define the `parseCommand()` function at the top level.

`read_input_byte()` returns a single byte as an `int` or it returns `None` if there is no data available.

So replace `readline()`, you would need to do something like this.

```python
...

CR = ord('\r')
LF = ord('\n')

...

async def read_line():
    line = bytearray()

    while True:
        b = read_input_byte()

        # no input was available yet
        if b is None:
           # give other tasks a chance to run
            await wait(0)
            # then check for another byte
            continue

        # ignore carriage return
        if b == CR:
            continue

        # line feed indicates end of line
        if b == LF:
            return str(line, 'utf8')

        line.append(b)
```

Then use it like this:

```python

async def main():
    while True:
        # Let PC know we are ready for a command
        print("OK")

        # Read all bytes
        command = await read_line()

        ...
```

**Comment by dlech** [comment]
Yes, any motor method that starts with `run_` will need an `await` (and the function that calls it needs to be `async`).
