### ISSUE TITLE
Bluetooth hub disconnects during firmware flash on MacOS

### ISSUE THREAD

**Issue by legolasse** [pybricks/pybricksdev#75]
The error is observed on the following setup:
OS: Apple M1 Pro, 14.4.1 (23E224)
Python: 3.10.4
Firmware: https://nightly.link/pybricks/pybricks-micropython/workflows/build/master/technichub-firmware-build-3343-git46f29c09.zip
pybricksdev: v1.0.0a46

Running: pybricksdev flash with the given firmware causes the error:

````
Creating firmware...
Searching for TECHNIC hub...
Found: DF4BFD20-FC05-F0E9-3AFD-8A9E3DAF5A90: LEGO Bootloader
Connecting to DF4BFD20-FC05-F0E9-3AFD-8A9E3DAF5A90: LEGO Bootloader
Connected successfully!
Erasing flash and starting update
  1%|█▏                                                                                                          | 2.21k/200k [00:30<45:56, 71.9B/s]
Traceback (most recent call last):
  File "/Users/ld/.pyenv/versions/3.10.4/bin/pybricksdev", line 8, in <module>
    sys.exit(main())
  File "/Users/ld/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pybricksdev/cli/__init__.py", line 383, in main
    asyncio.run(subparsers.choices[args.tool].tool.run(args))
  File "/Users/ld/.pyenv/versions/3.10.4/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ld/.pyenv/versions/3.10.4/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/ld/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pybricksdev/cli/flash.py", line 472, in flash_firmware
    await flash_ble(hub_kind, firmware, metadata)
  File "/Users/ld/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pybricksdev/cli/flash.py", line 327, in flash_ble
    await updater.flash(firmware, metadata)
  File "/Users/ld/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pybricksdev/flash.py", line 241, in flash
    result = await self.bootloader_request(
  File "/Users/ld/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pybricksdev/flash.py", line 160, in bootloader_request
    await self.write(data, request.write_with_response)
  File "/Users/ld/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pybricksdev/ble/__init__.py", line 149, in write
    await self.client.write_gatt_char(
  File "/Users/ld/.pyenv/versions/3.10.4/lib/python3.10/site-packages/bleak/__init__.py", line 659, in write_gatt_char
    await self._backend.write_gatt_char(char_specifier, data, response)
  File "/Users/ld/.pyenv/versions/3.10.4/lib/python3.10/site-packages/bleak/backends/corebluetooth/client.py", line 332, in write_gatt_char
    await self._delegate.write_characteristic(
  File "/Users/ld/.pyenv/versions/3.10.4/lib/python3.10/site-packages/bleak/backends/corebluetooth/PeripheralDelegate.py", line 192, in write_characteristic
    await future
bleak.exc.BleakError: disconnected
````

This issue currently makes PyBricks unavailable for the given OS/chip combo due to neither Chromium nor pybricksdev working.

**Comment by dlech** [comment]
If you have any other Bluetooth devices connected to your Mac, I would turn them all off and try again.

If that doesn't fix it, we would need Bluetooth packet logs to help troubleshoot. (see https://bleak.readthedocs.io/en/latest/troubleshooting.html#macos)
