### ISSUE TITLE
TimeoutError when running simple program via pybricksdev on Mac OS X

### ISSUE THREAD

**Issue by thomasbrus** [pybricks/pybricksdev#76]
Alright so I'll try to be as detailed as possible. I have this very simple program:

```python
from pybricks.hubs import TechnicHub
from pybricks.parameters import Color
from pybricks.tools import wait

print("Hello, World!")

# Initialize the hub.
hub = TechnicHub()

# Turn the light on and off 5 times.
for i in range(5):

    hub.light.on(Color.RED)
    wait(1000)

    hub.light.off()
    wait(500)
``` 

It works fine via https://code.pybricks.com/. Then I simply followed the pybricksdev instructions [over here](https://pybricks.com/projects/tutorials/dev/tools/vscode/) and ran the program.

For a few seconds the light on my brick is just blue (not blinking), as if it is frozen. It doesn't seem like the program is being executed. In the logs see it finds and connects to my technic hub, eventually disconnects and throws a timeout error.

I also captured the bluetooth traffic via PacketLogger by the way: [packetlog.zip](https://github.com/pybricks/pybricksdev/files/15138047/packetlog.zip)

Any help is appreciated 😄

```
$ pybricksdev -d run ble robot.py 
2024-04-27 13:31:30,171: DEBUG: asyncio: Using selector: KqueueSelector
Searching for any hub with Pybricks service...
2024-04-27 13:31:30,382: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManagerDidUpdateState_
2024-04-27 13:31:30,383: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Bluetooth powered on
2024-04-27 13:31:30,383: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: 'isScanning' changed
2024-04-27 13:31:30,409: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 13:31:30,410: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 13:31:30,412: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 05BFA874-E12D-21CD-CD37-5FE0DA16D4D3: LE_WH-1000XM4 @ RSSI: -37 (kCBAdvData <nsdict_keys(['kCBAdvDataTimestamp', 'kCBAdvDataServiceData', 'kCBAdvDataRxPrimaryPHY', 'kCBAdvDataIsConnectable', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataLocalName', 'kCBAdvDataServiceUUIDs'])>) and Central: <CBCentralManager: 0x7fb4ee3cddb0>
2024-04-27 13:31:30,413: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 05BFA874-E12D-21CD-CD37-5FE0DA16D4D3: LE_WH-1000XM4 @ RSSI: -38 (kCBAdvData <nsdict_keys(['kCBAdvDataTimestamp', 'kCBAdvDataServiceData', 'kCBAdvDataRxPrimaryPHY', 'kCBAdvDataIsConnectable', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataLocalName', 'kCBAdvDataServiceUUIDs'])>) and Central: <CBCentralManager: 0x7fb4ee3cddb0>
2024-04-27 13:31:30,435: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 13:31:30,436: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 13:31:30,436: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device A5249550-D5DE-09D0-9A80-1F521BB6FF7C: iPhone van Thomas @ RSSI: -69 (kCBAdvData <nsdict_keys(['kCBAdvDataIsConnectable', 'kCBAdvDataTimestamp', 'kCBAdvDataManufacturerData', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataTxPowerLevel', 'kCBAdvDataRxPrimaryPHY'])>) and Central: <CBCentralManager: 0x7fb4ee3cddb0>
2024-04-27 13:31:30,437: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device A5249550-D5DE-09D0-9A80-1F521BB6FF7C: iPhone van Thomas @ RSSI: -69 (kCBAdvData <nsdict_keys(['kCBAdvDataIsConnectable', 'kCBAdvDataTimestamp', 'kCBAdvDataManufacturerData', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataTxPowerLevel', 'kCBAdvDataRxPrimaryPHY'])>) and Central: <CBCentralManager: 0x7fb4ee3cddb0>
2024-04-27 13:31:30,613: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 13:31:30,614: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 13:31:30,616: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 05BFA874-E12D-21CD-CD37-5FE0DA16D4D3: LE_WH-1000XM4 @ RSSI: -38 (kCBAdvData <nsdict_keys(['kCBAdvDataTimestamp', 'kCBAdvDataServiceData', 'kCBAdvDataRxPrimaryPHY', 'kCBAdvDataIsConnectable', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataLocalName', 'kCBAdvDataServiceUUIDs'])>) and Central: <CBCentralManager: 0x7fb4ee3cddb0>
2024-04-27 13:31:30,616: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 05BFA874-E12D-21CD-CD37-5FE0DA16D4D3: LE_WH-1000XM4 @ RSSI: -38 (kCBAdvData <nsdict_keys(['kCBAdvDataTimestamp', 'kCBAdvDataServiceData', 'kCBAdvDataRxPrimaryPHY', 'kCBAdvDataIsConnectable', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataLocalName', 'kCBAdvDataServiceUUIDs'])>) and Central: <CBCentralManager: 0x7fb4ee3cddb0>
2024-04-27 13:31:30,639: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 13:31:30,639: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 13:31:30,640: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 166E8D19-D855-BB6F-9F52-C81E85EB1A39: Technic Hub A @ RSSI: -45 (kCBAdvData <nsdict_keys(['kCBAdvDataTimestamp', 'kCBAdvDataRxPrimaryPHY', 'kCBAdvDataServiceUUIDs', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataTxPowerLevel', 'kCBAdvDataIsConnectable'])>) and Central: <CBCentralManager: 0x7fb4ee3cddb0>
2024-04-27 13:31:30,640: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 166E8D19-D855-BB6F-9F52-C81E85EB1A39: Technic Hub A @ RSSI: -45 (kCBAdvData <nsdict_keys(['kCBAdvDataTimestamp', 'kCBAdvDataServiceData', 'kCBAdvDataRxPrimaryPHY', 'kCBAdvDataIsConnectable', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataLocalName', 'kCBAdvDataTxPowerLevel', 'kCBAdvDataServiceUUIDs'])>) and Central: <CBCentralManager: 0x7fb4ee3cddb0>
2024-04-27 13:31:30,641: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: 'isScanning' changed
2024-04-27 13:31:30,641: INFO: pybricksdev.connections: Connecting to 166E8D19-D855-BB6F-9F52-C81E85EB1A39
2024-04-27 13:31:30,641: DEBUG: bleak.backends.corebluetooth.client: CentralManagerDelegate  at <CentralManagerDelegate: 0x7fb4eadbdfe0>
2024-04-27 13:31:30,641: DEBUG: bleak.backends.corebluetooth.client: Connecting to BLE device @ 166E8D19-D855-BB6F-9F52-C81E85EB1A39
2024-04-27 13:31:31,011: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didConnectPeripheral_
2024-04-27 13:31:31,012: DEBUG: bleak.backends.corebluetooth.client: Retrieving services...
2024-04-27 13:31:32,210: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverServices_
2024-04-27 13:31:32,210: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Services discovered
2024-04-27 13:31:32,211: DEBUG: bleak.backends.corebluetooth.client: Retrieving characteristics for service 180A
2024-04-27 13:31:32,570: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverCharacteristicsForService_error_
2024-04-27 13:31:32,570: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Characteristics discovered
2024-04-27 13:31:32,571: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic 2A26
2024-04-27 13:31:32,571: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 13:31:32,571: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 10
2024-04-27 13:31:32,572: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic 2A28
2024-04-27 13:31:32,572: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 13:31:32,573: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 12
2024-04-27 13:31:32,573: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic 2A50
2024-04-27 13:31:32,573: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 13:31:32,573: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 14
2024-04-27 13:31:32,574: DEBUG: bleak.backends.corebluetooth.client: Retrieving characteristics for service C5F50001-8280-46DA-89F4-6D8051E4AEEF
2024-04-27 13:31:32,811: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverCharacteristicsForService_error_
2024-04-27 13:31:32,812: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Characteristics discovered
2024-04-27 13:31:32,812: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic C5F50002-8280-46DA-89F4-6D8051E4AEEF
2024-04-27 13:31:32,930: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 13:31:32,931: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 17
2024-04-27 13:31:32,932: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic C5F50003-8280-46DA-89F4-6D8051E4AEEF
2024-04-27 13:31:32,932: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 13:31:32,933: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 20
2024-04-27 13:31:32,933: DEBUG: bleak.backends.corebluetooth.client: Retrieving characteristics for service 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
2024-04-27 13:31:33,171: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverCharacteristicsForService_error_
2024-04-27 13:31:33,171: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Characteristics discovered
2024-04-27 13:31:33,172: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic 6E400002-B5A3-F393-E0A9-E50E24DCCA9E
2024-04-27 13:31:33,172: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 13:31:33,173: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 23
2024-04-27 13:31:33,173: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic 6E400003-B5A3-F393-E0A9-E50E24DCCA9E
2024-04-27 13:31:33,290: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 13:31:33,291: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 25
2024-04-27 13:31:33,291: DEBUG: bleak.backends.corebluetooth.client: Services resolved for BleakClientCoreBluetooth (166E8D19-D855-BB6F-9F52-C81E85EB1A39)
2024-04-27 13:31:33,291: INFO: pybricksdev.connections: Connected successfully!
2024-04-27 13:31:33,410: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didUpdateValueForCharacteristic_error_
2024-04-27 13:31:33,410: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Read characteristic value
2024-04-27 13:31:33,410: DEBUG: bleak.backends.corebluetooth.client: Read Characteristic 00002a28-0000-1000-8000-00805f9b34fb : bytearray(b'1.3.0')
2024-04-27 13:31:33,530: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didUpdateValueForCharacteristic_error_
2024-04-27 13:31:33,530: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Read characteristic value
2024-04-27 13:31:33,531: DEBUG: bleak.backends.corebluetooth.client: Read Characteristic 00002a50-0000-1000-8000-00805f9b34fb : bytearray(b'\x01\x97\x03\x80\x00\x00\x00')
2024-04-27 13:31:33,649: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didUpdateNotificationStateForCharacteristic_error_
2024-04-27 13:31:33,650: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Character Notify Update
2024-04-27 13:31:33,769: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didUpdateNotificationStateForCharacteristic_error_
2024-04-27 13:31:33,769: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Character Notify Update
2024-04-27 13:31:33,773: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didUpdateValueForCharacteristic_error_
2024-04-27 13:31:33,783: DEBUG: bleak.backends.corebluetooth.client: Write Characteristic 6e400002-b5a3-f393-e0a9-e50e24dcca9e : b'\xeb\x00\x00\x00'
2024-04-27 13:31:34,250: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didUpdateValueForCharacteristic_error_
2024-04-27 13:31:34,284: INFO: pybricksdev.connections: Disconnecting...
2024-04-27 13:31:34,285: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDisconnectPeripheral_error_
2024-04-27 13:31:34,285: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Peripheral Device disconnected!
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/thomasbrus/Code/lego-camera/.venv/bin/pybricksdev", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/thomasbrus/Code/lego-camera/.venv/lib/python3.12/site-packages/pybricksdev/cli/__init__.py", line 431, in main
    asyncio.run(subparsers.choices[args.tool].tool.run(args))
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/thomasbrus/Code/lego-camera/.venv/lib/python3.12/site-packages/pybricksdev/cli/__init__.py", line 202, in run
    await hub.run(script_path, args.wait)
  File "/Users/thomasbrus/Code/lego-camera/.venv/lib/python3.12/site-packages/pybricksdev/connections.py", line 367, in run
    await self.send_block(length)
  File "/Users/thomasbrus/Code/lego-camera/.venv/lib/python3.12/site-packages/pybricksdev/connections.py", line 340, in send_block
    await asyncio.wait_for(self.checksum_ready.wait(), timeout=0.5)
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
```

**Comment by dlech** [comment]
What firmware version and pybricksdev version are you using? I seen nordic uart stuff in the packet logs, so unless you are using an older firmware, I think the pybricksdev version may be too old.

**Comment by thomasbrus** [comment]
@dlech firmware: 3.5.0, pybricksdev: v1.0.0a17. That's just what I got via `pip install pybricksdev`, not sure if that's the latest version though..

**Comment by dlech** [comment]
Or 3.10.

**Comment by thomasbrus** [comment]
Alright I'll give that a try, thanks 👍
