### ISSUE TITLE
Timeout error connecting to hub

### ISSUE THREAD

**Issue by ninaschmelk** [pybricks/pybricksdev#77]
## Summary
We are trying to switch from using the pybricks built-in IDE to VSCode. I am **unable to connect and upload code** to my Spike Prime hub with the following errors below.

## Have confirmed
* Completed firmware update from beta.pybricks.com
* Named the hub `pyswirle` and can successfully connect and upload code in pybricks IDA
* Attempting to connect and upload by name `--name "pyswirle"` or omitting the name results in similar timeout error
* Hub is on (and works with pybricks IDE to upload code)

## Environment
Mac OS: Sonoma14.4.1
Pybricks: 3.5
Pybricksdev: 1.0.0a17

### Without a named hub

```
(.venv) nina@Ninas-MacBook-Pro masterpiece-2023-2024 % pybricksdev --debug run ble master_missions.py
2024-04-27 15:52:46,008: DEBUG: asyncio: Using selector: KqueueSelector
Searching for any hub with Pybricks service...
2024-04-27 15:52:46,252: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManagerDidUpdateState_
2024-04-27 15:52:46,252: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Bluetooth powered on
2024-04-27 15:52:46,253: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: 'isScanning' changed
2024-04-27 15:52:46,286: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 15:52:46,286: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 15:52:46,289: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 50D0BE37-3CEC-418F-3E78-6BFC97462916: Hatch Rest @ RSSI: -102 (kCBAdvData <nsdict_keys(['kCBAdvDataTimestamp', 'kCBAdvDataServiceData', 'kCBAdvDataRxPrimaryPHY', 'kCBAdvDataIsConnectable', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataLocalName', 'kCBAdvDataServiceUUIDs'])>) and Central: <CBCentralManager: 0x7f93551cf6f0>
2024-04-27 15:52:46,290: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device C3E4509F-ACB0-E00A-0810-89E17F099DAD: None @ RSSI: -89 (kCBAdvData <nsdict_keys(['kCBAdvDataIsConnectable', 'kCBAdvDataTimestamp', 'kCBAdvDataManufacturerData', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataTxPowerLevel', 'kCBAdvDataRxPrimaryPHY'])>) and Central: <CBCentralManager: 0x7f93551cf6f0>
2024-04-27 15:52:46,307: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 15:52:46,307: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 15:52:46,308: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 18D791B2-57C5-9CC5-3618-AF93AE4D0CFF: pyswirle @ RSSI: -44 (kCBAdvData <nsdict_keys(['kCBAdvDataTimestamp', 'kCBAdvDataRxPrimaryPHY', 'kCBAdvDataServiceUUIDs', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataTxPowerLevel', 'kCBAdvDataIsConnectable'])>) and Central: <CBCentralManager: 0x7f93551cf6f0>
2024-04-27 15:52:46,309: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 18D791B2-57C5-9CC5-3618-AF93AE4D0CFF: pyswirle @ RSSI: -44 (kCBAdvData <nsdict_keys(['kCBAdvDataTimestamp', 'kCBAdvDataServiceData', 'kCBAdvDataRxPrimaryPHY', 'kCBAdvDataIsConnectable', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataLocalName', 'kCBAdvDataTxPowerLevel', 'kCBAdvDataServiceUUIDs'])>) and Central: <CBCentralManager: 0x7f93551cf6f0>
2024-04-27 15:52:46,309: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: 'isScanning' changed
2024-04-27 15:52:46,309: INFO: pybricksdev.connections: Connecting to 18D791B2-57C5-9CC5-3618-AF93AE4D0CFF
2024-04-27 15:52:46,309: DEBUG: bleak.backends.corebluetooth.client: CentralManagerDelegate  at <CentralManagerDelegate: 0x7f93551b0320>
2024-04-27 15:52:46,309: DEBUG: bleak.backends.corebluetooth.client: Connecting to BLE device @ 18D791B2-57C5-9CC5-3618-AF93AE4D0CFF
2024-04-27 15:52:46,443: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didConnectPeripheral_
2024-04-27 15:52:46,444: DEBUG: bleak.backends.corebluetooth.client: Retrieving services...
2024-04-27 15:52:46,608: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverServices_
2024-04-27 15:52:46,608: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Services discovered
2024-04-27 15:52:46,609: DEBUG: bleak.backends.corebluetooth.client: Retrieving characteristics for service 180A
2024-04-27 15:52:46,638: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverCharacteristicsForService_error_
2024-04-27 15:52:46,638: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Characteristics discovered
2024-04-27 15:52:46,638: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic 2A26
2024-04-27 15:52:46,639: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 15:52:46,639: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 5
2024-04-27 15:52:46,640: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic 2A28
2024-04-27 15:52:46,640: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 15:52:46,640: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 7
2024-04-27 15:52:46,641: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic 2A50
2024-04-27 15:52:46,641: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 15:52:46,641: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 9
2024-04-27 15:52:46,642: DEBUG: bleak.backends.corebluetooth.client: Retrieving characteristics for service C5F50001-8280-46DA-89F4-6D8051E4AEEF
2024-04-27 15:52:46,668: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverCharacteristicsForService_error_
2024-04-27 15:52:46,669: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Characteristics discovered
2024-04-27 15:52:46,669: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic C5F50002-8280-46DA-89F4-6D8051E4AEEF
2024-04-27 15:52:46,698: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 15:52:46,698: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 12
2024-04-27 15:52:46,699: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic C5F50003-8280-46DA-89F4-6D8051E4AEEF
2024-04-27 15:52:46,700: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 15:52:46,700: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 15
2024-04-27 15:52:46,700: DEBUG: bleak.backends.corebluetooth.client: Retrieving characteristics for service 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
2024-04-27 15:52:46,728: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverCharacteristicsForService_error_
2024-04-27 15:52:46,728: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Characteristics discovered
2024-04-27 15:52:46,729: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic 6E400002-B5A3-F393-E0A9-E50E24DCCA9E
2024-04-27 15:52:46,729: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 15:52:46,729: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 18
2024-04-27 15:52:46,730: DEBUG: bleak.backends.corebluetooth.client: Retrieving descriptors for characteristic 6E400003-B5A3-F393-E0A9-E50E24DCCA9E
2024-04-27 15:52:46,758: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didDiscoverDescriptorsForCharacteristic_error_
2024-04-27 15:52:46,758: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Descriptor discovered 20
2024-04-27 15:52:46,758: DEBUG: bleak.backends.corebluetooth.client: Services resolved for BleakClientCoreBluetooth (18D791B2-57C5-9CC5-3618-AF93AE4D0CFF)
2024-04-27 15:52:46,758: INFO: pybricksdev.connections: Connected successfully!
2024-04-27 15:52:46,787: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didUpdateValueForCharacteristic_error_
2024-04-27 15:52:46,788: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Read characteristic value
2024-04-27 15:52:46,788: DEBUG: bleak.backends.corebluetooth.client: Read Characteristic 00002a28-0000-1000-8000-00805f9b34fb : bytearray(b'1.3.0')
2024-04-27 15:52:46,817: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didUpdateValueForCharacteristic_error_
2024-04-27 15:52:46,818: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Read characteristic value
2024-04-27 15:52:46,818: DEBUG: bleak.backends.corebluetooth.client: Read Characteristic 00002a50-0000-1000-8000-00805f9b34fb : bytearray(b'\x01\x97\x03\x81\x00\x00\x00')
2024-04-27 15:52:46,848: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didUpdateNotificationStateForCharacteristic_error_
2024-04-27 15:52:46,848: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Character Notify Update
2024-04-27 15:52:46,879: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didUpdateNotificationStateForCharacteristic_error_
2024-04-27 15:52:46,879: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: Character Notify Update
2024-04-27 15:52:46,879: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didUpdateValueForCharacteristic_error_
2024-04-27 15:52:46,912: DEBUG: bleak.backends.corebluetooth.client: Write Characteristic 6e400002-b5a3-f393-e0a9-e50e24dcca9e : b'k\x0e\x00\x00'
2024-04-27 15:52:47,371: DEBUG: bleak.backends.corebluetooth.PeripheralDelegate: peripheral_didUpdateValueForCharacteristic_error_
2024-04-27 15:52:47,417: INFO: pybricksdev.connections: Disconnecting...
2024-04-27 15:52:47,418: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDisconnectPeripheral_error_
2024-04-27 15:52:47,418: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Peripheral Device disconnected!
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nina/Sites/masterpiece-2023-2024/.venv/bin/pybricksdev", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/nina/Sites/masterpiece-2023-2024/.venv/lib/python3.12/site-packages/pybricksdev/cli/__init__.py", line 431, in main
    asyncio.run(subparsers.choices[args.tool].tool.run(args))
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/nina/Sites/masterpiece-2023-2024/.venv/lib/python3.12/site-packages/pybricksdev/cli/__init__.py", line 202, in run
    await hub.run(script_path, args.wait)
  File "/Users/nina/Sites/masterpiece-2023-2024/.venv/lib/python3.12/site-packages/pybricksdev/connections.py", line 367, in run
    await self.send_block(length)
  File "/Users/nina/Sites/masterpiece-2023-2024/.venv/lib/python3.12/site-packages/pybricksdev/connections.py", line 340, in send_block
    await asyncio.wait_for(self.checksum_ready.wait(), timeout=0.5)
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
```

### With a named hub

```
(.venv) nina@Ninas-MacBook-Pro masterpiece-2023-2024 % pybricksdev --debug run ble --name "pyswirle" master_missions.py
2024-04-27 15:53:49,100: DEBUG: asyncio: Using selector: KqueueSelector
Searching for pyswirle...
2024-04-27 15:53:49,409: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManagerDidUpdateState_
2024-04-27 15:53:49,410: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Bluetooth powered on
2024-04-27 15:53:49,410: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: 'isScanning' changed
2024-04-27 15:53:49,442: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 15:53:49,445: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 01302B65-D00E-5C54-DF94-AA407CC1352C: None @ RSSI: -84 (kCBAdvData <nsdict_keys(['kCBAdvDataManufacturerData', 'kCBAdvDataTimestamp', 'kCBAdvDataIsConnectable', 'kCBAdvDataRxPrimaryPHY', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataTxPowerLevel', 'kCBAdvDataServiceUUIDs'])>) and Central: <CBCentralManager: 0x7fa70ba4f7f0>
2024-04-27 15:53:49,460: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 15:53:49,461: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 15:53:49,463: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 89B51201-88DE-2CD1-06C4-43C998AFE012: None @ RSSI: -86 (kCBAdvData <nsdict_keys(['kCBAdvDataIsConnectable', 'kCBAdvDataManufacturerData', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataTimestamp', 'kCBAdvDataRxPrimaryPHY'])>) and Central: <CBCentralManager: 0x7fa70ba4f7f0>
2024-04-27 15:53:49,463: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 15:53:49,464: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 15:53:49,465: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 89B51201-88DE-2CD1-06C4-43C998AFE012: None @ RSSI: -86 (kCBAdvData <nsdict_keys(['kCBAdvDataIsConnectable', 'kCBAdvDataManufacturerData', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataTimestamp', 'kCBAdvDataRxPrimaryPHY'])>) and Central: <CBCentralManager: 0x7fa70ba4f7f0>
2024-04-27 15:53:49,465: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 973BBC82-EA01-04B5-BD3D-27242E51178B: None @ RSSI: -92 (kCBAdvData <nsdict_keys(['kCBAdvDataIsConnectable', 'kCBAdvDataManufacturerData', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataTimestamp', 'kCBAdvDataRxPrimaryPHY'])>) and Central: <CBCentralManager: 0x7fa70ba4f7f0>
2024-04-27 15:53:49,466: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 4215CCD5-7F5C-0E1A-D01E-B028C1423922: None @ RSSI: -90 (kCBAdvData <nsdict_keys(['kCBAdvDataIsConnectable', 'kCBAdvDataManufacturerData', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataTimestamp', 'kCBAdvDataRxPrimaryPHY'])>) and Central: <CBCentralManager: 0x7fa70ba4f7f0>
2024-04-27 15:53:49,470: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 15:53:49,471: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 15:53:49,471: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDiscoverPeripheral_advertisementData_RSSI_
2024-04-27 15:53:49,472: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 18D791B2-57C5-9CC5-3618-AF93AE4D0CFF: pyswirle @ RSSI: -101 (kCBAdvData <nsdict_keys(['kCBAdvDataTimestamp', 'kCBAdvDataServiceData', 'kCBAdvDataRxPrimaryPHY', 'kCBAdvDataIsConnectable', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataLocalName', 'kCBAdvDataTxPowerLevel', 'kCBAdvDataServiceUUIDs'])>) and Central: <CBCentralManager: 0x7fa70ba4f7f0>
2024-04-27 15:53:49,472: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 059BC33F-D780-72F4-2104-A8E240EA5700: None @ RSSI: -85 (kCBAdvData <nsdict_keys(['kCBAdvDataIsConnectable', 'kCBAdvDataManufacturerData', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataTimestamp', 'kCBAdvDataRxPrimaryPHY'])>) and Central: <CBCentralManager: 0x7fa70ba4f7f0>
2024-04-27 15:53:49,473: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Discovered device 059BC33F-D780-72F4-2104-A8E240EA5700: None @ RSSI: -85 (kCBAdvData <nsdict_keys(['kCBAdvDataIsConnectable', 'kCBAdvDataManufacturerData', 'kCBAdvDataRxSecondaryPHY', 'kCBAdvDataTimestamp', 'kCBAdvDataRxPrimaryPHY'])>) and Central: <CBCentralManager: 0x7fa70ba4f7f0>
2024-04-27 15:53:49,473: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: 'isScanning' changed
2024-04-27 15:53:49,473: INFO: pybricksdev.connections: Connecting to 18D791B2-57C5-9CC5-3618-AF93AE4D0CFF
2024-04-27 15:53:49,473: DEBUG: bleak.backends.corebluetooth.client: CentralManagerDelegate  at <CentralManagerDelegate: 0x7fa70e2957c0>
2024-04-27 15:53:49,474: DEBUG: bleak.backends.corebluetooth.client: Connecting to BLE device @ 18D791B2-57C5-9CC5-3618-AF93AE4D0CFF
2024-04-27 15:53:59,475: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Connection timed out after 10.0 seconds.
2024-04-27 15:53:59,476: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: centralManager_didDisconnectPeripheral_error_
2024-04-27 15:53:59,477: DEBUG: bleak.backends.corebluetooth.CentralManagerDelegate: Peripheral Device disconnected!
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nina/Sites/masterpiece-2023-2024/.venv/bin/pybricksdev", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/nina/Sites/masterpiece-2023-2024/.venv/lib/python3.12/site-packages/pybricksdev/cli/__init__.py", line 431, in main
    asyncio.run(subparsers.choices[args.tool].tool.run(args))
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/nina/Sites/masterpiece-2023-2024/.venv/lib/python3.12/site-packages/pybricksdev/cli/__init__.py", line 199, in run
    await hub.connect(device_or_address)
  File "/Users/nina/Sites/masterpiece-2023-2024/.venv/lib/python3.12/site-packages/pybricksdev/connections.py", line 294, in connect
    await self.client.connect(disconnected_callback=disconnected_handler)
  File "/Users/nina/Sites/masterpiece-2023-2024/.venv/lib/python3.12/site-packages/bleak/backends/corebluetooth/client.py", line 118, in connect
    await manager.connect(self._peripheral, disconnect_callback, timeout=timeout)
  File "/Users/nina/Sites/masterpiece-2023-2024/.venv/lib/python3.12/site-packages/bleak/backends/corebluetooth/CentralManagerDelegate.py", line 157, in connect
    await asyncio.wait_for(future, timeout=timeout)
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
```

**Comment by dlech** [comment]
Duplicate of #76. pybricksdev is not currently compatible with Python 3.12. You need to use 3.10.

**Comment by ninaschmelk** [comment]
@dlech thank you! sorry, had missed that earlier post. upgraded to `pybricksdev==1.0.0a46` and downgraded python to 3.10, and works perfectly! MANY THANKS for the lightening fast help

**Comment by ninaschmelk** [comment]
resolution:
`pybricksdev==1.0.0a46`
`python<3.11`
